name: backend-actions
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  backend-actions:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '16'
      - run: npm install -g bats
      - run: bats -v
      - run: echo 'Test config'

      - name: Install modules
        run: npm install --prefix backend

      - name: Backend e2e Tests
        run: npm run test:e2e --prefix backend

      - name: Build
        run: npm run build --prefix backend
